openapi: "3.0.1"
info:
  title: "AMIElevator"
  description: "send commands to the elevator"
  version: '1'
servers:
- url: "https://localhost:8080"
paths:
  /CallToFloor:
    post:
      summary: "CallToFloor"
      operationId: "CallToFloor"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FloorNumber"
        required: true
      responses:
        '202':  
          description: "Successful operation"
        '400':
          description: "Error occurred"
components:
  schemas:
    FloorNumber:
      type: "object"
      properties:
        floor:
          type: "integer"
          minimum: 1
          maximum: 10
      example:
        floor: 5